##1. How to extract all odd numbers from arr?

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2=arr[arr % 2 == 1]
print(f"Odd numbers from the Array are : {arr2}")

Odd numbers from the Array are : [1 3 5 7 9]


## 2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(f"Modified array: {arr}")

Modified array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 3. Convert a 1D array to a 2D array with 2 rows

In [ ]:
import numpy as np
arr=np.arange(10)
arr1 = arr.reshape(2, 5)
print (f"After reshaping : \n{arr1}")

After reshaping : 
[[0 1 2 3 4]
 [5 6 7 8 9]]


##4. Stack arrays a and b vertically


In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 5. Stack the arrays a and b horizontally.

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 6.How to get the common items between two python numpy arrays?
Get the common items between a and b

In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Original arrays :\n{a},{b}")
c = np.intersect1d(a,b)
print(f"Common values : {c}")

Original arrays :
[1 2 3 2 3 4 3 4 5 6],[ 7  2 10  2  7  4  9  4  9  8]
Common values : [2 4]


## 7.How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


##8. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of a and b match


In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(a==b)
print(c)

(array([1, 3, 5, 7]),)


## 9. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a

In [ ]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])